name: extract_id

on:
  schedule:
    - cron:  '0 * * * *' # At minute 0 past every hour.
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  run-script:
    name: Execute Python Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Specify the Python version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run Python Script
        run: python python/extract_id.py

      # If you need to publish the results to GitHub
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
