name: Run Python Script, Capture Screenshots, Save IDs, and Commit Results

on:
  workflow_dispatch:

jobs:
  run-commit-capture:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run the script
      env:
        FB_EMAIL: ${{ secrets.FB_EMAIL }}
        FB_PASSWORD: ${{ secrets.FB_PASSWORD }}
      run: python python/test.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Add script outputs and logs" || echo "No changes to commit"
        git push
