name: Run Python Script, Capture Screenshots, Save IDs, and Commit Results

on:
  workflow_dispatch:

jobs:
  run-commit-capture:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install

    - name: Run the script
      run: python python/test.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add screenshot1.png screenshot2.png extracted_ids.txt script_log.txt
        git commit -m "Add script outputs and logs" || echo "No changes to commit"
        git push
