name: Run Python Script, Capture Screenshots, and Save IDs

on:
  workflow_dispatch:

jobs:
  run-and-capture:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install

    - name: Run the script
      run: python path/to/your_script.py

    - name: Upload Screenshot 1
      uses: actions/upload-artifact@v2
      with:
        name: screenshot1
        path: screenshot1.png

    - name: Upload Screenshot 2
      uses: actions/upload-artifact@v2
      with:
        name: screenshot2
        path: screenshot2.png

    - name: Upload Extracted IDs
      uses: actions/upload-artifact@v2
      with:
        name: extracted-ids
        path: extracted_ids.txt
